spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
app.cors.allowed-origins=https://www.terpplanner.com/
clerk.jwks-url=https://clerk.terpplanner.com/.well-known/jwks.json


spring.datasource.hikari.minimum-idle=1              # keep at least one connection around
spring.datasource.hikari.maximum-pool-size=5         # low max pool size
spring.datasource.hikari.idle-timeout=300000         # 5 min before idle connection may be closed
spring.datasource.hikari.max-lifetime=1800000        # 30 min max lifetime per connection
spring.datasource.hikari.connection-timeout=30000    # 30s to wait for a connection