spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/four_year_planner}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:WillGraham}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}

server.error.include-message=always
spring.application.name=four-year-planner

clerk.jwks-url=${CLERK_JWKS_URL:https://thankful-dolphin-88.clerk.accounts.dev/.well-known/jwks.json}

openai.api.base-url=${OPENAI_API_BASE_URL:https://api.openai.com/v1}
openai.api.key=${OPENAI_API_KEY:}
openai.model=${OPENAI_MODEL:gpt-5.4-nano}
