spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=never
app.cors.allowed-origins=https://www.terpplanner.com
clerk.jwks-url=https://clerk.terpplanner.com/.well-known/jwks.json
app.guest.cookie-domain=${APP_GUEST_COOKIE_DOMAIN:}
app.guest.cookie-secure=${APP_GUEST_COOKIE_SECURE:true}


spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
